<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['groups_add_user_defined_group'] = 'Добавить определенного пользователя в группу';
$lang['groups_app_description'] = 'Приложение "Группы" позволяет администратору создавать, удалять и изменять группы в системе. Группы могут быть использованы для эффективного управления разрешениями доступа к ресурсам сервера.';
$lang['groups_app_name'] = 'Группы';
$lang['groups_app_policies'] = 'Политика App';
$lang['groups_builtin_groups'] = 'Встроенная группа';
$lang['groups_description'] = 'Описание';
$lang['groups_description_invalid'] = 'Описание является недействительным.';
$lang['groups_edit_members'] = 'Редактировать пользователя';
$lang['groups_global_policy'] = 'Глобальная политика';
$lang['groups_group'] = 'Группа';
$lang['groups_group_already_exists'] = 'Группа уже существует.';
$lang['groups_group_id'] = 'ID Группы';
$lang['groups_group_is_reserved_for_system'] = 'Группа зарезервирована для системы.';
$lang['groups_group_is_reserved_for_windows'] = 'Группа зарезервирован для интеграции с ОС Windows.';
$lang['groups_group_manager'] = 'Менеджер группы';
$lang['groups_group_members'] = 'Пользователь группы';
$lang['groups_group_name'] = 'Имя группы';
$lang['groups_group_name_invalid'] = 'Название группы является недействительным.';
$lang['groups_group_not_found'] = 'Группа не найдена.';
$lang['groups_groups'] = 'Группы';
$lang['groups_members'] = 'Пользователи';
$lang['groups_no_user_defined_groups_warning'] = 'Все пользовательские группы имеют настроенную политику. Если вы хотели бы добавить новую политику, пожалуйста, добавьте несколько групп.';
$lang['groups_plugin_groups'] = 'Плагин группы';
$lang['groups_policy'] = 'Политика';
$lang['groups_policy_name'] = 'Имя политики';
$lang['groups_policy_name_invalid'] = 'Имя политики является недействительным.';
$lang['groups_spaces_not_allowed_in_group_names'] = 'Пробелы не допускаются в именах групп.';
$lang['groups_user_defined_groups'] = 'Пользователи в определенной группе';
$lang['groups_view_members'] = 'Смотреть пользователей';
$lang['groups_windows_groups'] = 'Windows группы';
