<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['groups_add_user_defined_group'] = 'Använd definierade grupper';
$lang['groups_app_description'] = 'Grupp-appen ger administratören möjligheten att skapa, radera och ändra grupper på systemet.   Grupper kan användas till att effektivt hanterar behörigheter för att komma åt tjänster på servern.';
$lang['groups_app_name'] = 'Grupper';
$lang['groups_app_policies'] = 'Appens policy';
$lang['groups_builtin_groups'] = 'Inbyggda grupper';
$lang['groups_description'] = 'Beskrivning';
$lang['groups_description_invalid'] = 'Beskrivningen är ogiltig.';
$lang['groups_edit_members'] = 'Andra medlemmar';
$lang['groups_global_policy'] = 'Global policy';
$lang['groups_group'] = 'Grupp';
$lang['groups_group_already_exists'] = 'Gruppen finns redan.';
$lang['groups_group_id'] = 'Gruppens ID';
$lang['groups_group_is_reserved_for_system'] = 'Gruppen är reserverad för systemet.';
$lang['groups_group_is_reserved_for_windows'] = 'Gruppen är reserverad för integration med Windows.';
$lang['groups_group_manager'] = 'Grupphanterare';
$lang['groups_group_members'] = 'Gruppmedlemmar';
$lang['groups_group_name'] = 'Gruppens namn';
$lang['groups_group_name_invalid'] = 'Gruppnamnet är ogiltigt.';
$lang['groups_group_not_found'] = 'Gruppen hittades inte.';
$lang['groups_groups'] = 'Grupper';
$lang['groups_members'] = 'Medlemmar';
$lang['groups_no_user_defined_groups_warning'] = 'All the user defined groups have a configured policy.  If you would like to add a new policy, please add more groups.';
$lang['groups_plugin_groups'] = 'Tillägg för grupper';
$lang['groups_policy'] = 'Policy';
$lang['groups_policy_name'] = 'Namn på policyn';
$lang['groups_policy_name_invalid'] = 'Policy name is invalid.';
$lang['groups_spaces_not_allowed_in_group_names'] = 'Mellanslag är inte tillåtet i gruppnamn.';
$lang['groups_user_defined_groups'] = 'Använd definierade grupper';
$lang['groups_view_members'] = 'Visa medlemmar';
$lang['groups_windows_groups'] = 'Windowsgrupper';
