<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['groups_add_user_defined_group'] = 'Grupy zdefiniowane przez użytkownika';
$lang['groups_app_description'] = 'Aplikacja grup pozwala administratorom tworzyć, usuwać i modyfikować grupy w Twoim systemie.  Grupy mogą być używana dla efektywnego zarządzania zezwoleniami na dostęp do zasobów serwera.';
$lang['groups_app_name'] = 'Grupy';
$lang['groups_app_policies'] = 'Reguły aplikacji';
$lang['groups_builtin_groups'] = 'Grupy wbudowane';
$lang['groups_description'] = 'Opis';
$lang['groups_description_invalid'] = 'Wprowadzony opis jest nieprawidłowy.';
$lang['groups_edit_members'] = 'Edytuj członków';
$lang['groups_global_policy'] = 'Reguła globalna';
$lang['groups_group'] = 'Grupa';
$lang['groups_group_already_exists'] = 'Taka grupa już istnieje.';
$lang['groups_group_id'] = 'ID grupy';
$lang['groups_group_is_reserved_for_system'] = 'Ta grupa jest zarezerwowana dla systemu.';
$lang['groups_group_is_reserved_for_windows'] = 'Ta grupa jest zarezerwowana dla integracji z systemem Windows.';
$lang['groups_group_manager'] = 'Manager grup';
$lang['groups_group_members'] = 'Członkowie grup';
$lang['groups_group_name'] = 'Nazwa grupy';
$lang['groups_group_name_invalid'] = 'Podana nazwa grupy jest nieprawidłowa.';
$lang['groups_group_not_found'] = 'Grupa nie została znaleziona.';
$lang['groups_groups'] = 'Grupy';
$lang['groups_members'] = 'Członkowie';
$lang['groups_no_user_defined_groups_warning'] = 'All the user defined groups have a configured policy.  If you would like to add a new policy, please add more groups.';
$lang['groups_plugin_groups'] = 'Grupy wtyczek';
$lang['groups_policy'] = 'Policy';
$lang['groups_policy_name'] = 'Nazwa reguły';
$lang['groups_policy_name_invalid'] = 'Policy name is invalid.';
$lang['groups_spaces_not_allowed_in_group_names'] = 'Spacje nie są dozwolone w nazwach grup.';
$lang['groups_user_defined_groups'] = 'Grupy zdefiniowane przez użytkownika';
$lang['groups_view_members'] = 'Widok członków';
$lang['groups_windows_groups'] = 'Grupy Windows';
